### ISSUE TITLE
unwanted conversion of underlines to spaces in filenames in rubyripper 0.8

### ISSUE THREAD

**Issue by grattle** [bleskodev/rubyripper#628]
Using rubyripper 0.80rc1, current today, in preferences my Base Directory '/big/new_music/rubyrip_rips/' becomes '/big/new music/rubyrip rips/' in the ripped files. Underscores replaced by spaces. No such issue with your previous version 0.7 in its various incarnations.

Other than setting my Base Directory, my CDROM offset, and ripping only to flac, everything has been left at default. 

Have I not set something correctly? Or just a programing oops in the new version? Or user error?

bleskodev, thanks for the great job you have done keeping this indispensable program alive.

**Comment by bleskodev** [comment]
Hi, thanks for your kind words.
Yes I see where is the problem. Currently, if you want to keep underscores in your path (and replace the existing spaces!), you need to check the 'Replace spaces with underscores in file names' check box under Codecs tab in the preferences. 
By default this checkbox is not checked so, surprisingly, the underscores are removed! 
It seems this is by design, although I don't really know the reason (there are unit tests which confirm this behavior and it seems this behavior was (is?) wanted).

**Comment by bleskodev** [comment]
Of course, you are absolutely right. The behavior is not logical, I completely agree.
I have no idea why it was coded like this; a bug or a weird feature?
I'll try to analyze the consequences of changing the existing behavior to something more conventional.

**Comment by bleskodev** [comment]
Hi, I have changed the behavior of the option in question; it should now behave as expected (do nothing if not activated).
Thanks for reporting this issue!
